//topics
let topicArray = [
    "companies that start with 'E'",
    "parts of a PC",
    "male names that start with 'V'",
    "Names that start with 'V'",
    "Names that start with 'E'",
    "Cloths ",
    "songs by Frank Sinatra",
    "songs by David Bowie",
    "cold countries ",
    "Russian women names ",
    "Names that start with 'O'",
    "podcasts on spotify",
    "things you mix with wine",
    "Weapons you can't shoot with",
    "Figures from Family Guy ",
    "programming Languages",
    "Types of tea ",
    "Skate Terms ",
    "companies that start with 'C'",
    "Pieces of Shakespeare ",
    "jobs that start with 'G'",
    "songs by Freddie Mercury",
    "things you mix with rum",
    "movies starring Samuel L. Jackson",
    "female names that start with 'I'",
    "Football teams in the Champions League ",
    "Cutlery items ",
    "countries that start with 'N'",
    "Things that stink ",
    "female names that start with 'U'",
    "Figures from Asterix ",
    "male names that start with 'P'",
    "members of the Beatles",
    "Card games ",
    "Figures from the Simpsons ",
    "colors in a rainbow ",
    "pokemon",
    "Bones ",
    "What sticks ",
    "female names that start with 'M'",
    "Swiss cantons ",
    "countries that start with 'B'",
    "monopoly variants",
    "female names that start with 'H'",
    "Percussion instruments ",
    "female names that start with 'S'",
    "countries that start with 'I'",
    "Christmas carols ",
    "cities in the USA ",
    "Rivers in Europe",
    "companies that start with 'H'",
    "english speaking countries",
    "companies that start with 'F'",
    "movies starring Tom Hanks",
    "Classical plays ",
    "countries that start with 'G'",
    "countries that start with 'C'",
    "what can you write on ",
    "female names that start with 'R'",
    "male names that start with 'J'",
    "tree species",
    "things that are black ",
    "Names that start with 'K'",
    "female names that start with 'W'",
    "words with 'over' ",
    "Names that start with 'M'",
    "Politicians in World War II ",
    "female names that start with 'O'",
    "female names that start with 'V'",
    "Common American surnames ",
    "companies that start with 'T'",
    "Streaming services ",
    "Athletics Disciplines ",
    "songs by Bruce Springteen",
    "jobs that start with 'J'",
    "Things that are brown ",
    "Typical German food ",
    "Spaceship names ",
    "male names that start with 'L'",
    "movies starring Leonardo DiCaprio",
    "objects in the bathroom ",
    "James Bond films ",
    "Exotic fruits ",
    "male names that start with 'W'",
    "Things that are black ",
    "Comic heroes ",
    "Painter's equipment ",
    "female names that start with 'E'",
    "international airports",
    "Words with 'old' ",
    "Indian tribes ",
    "dictators ",
    "companies that start with 'R'",
    "jobs that start with 'D'",
    "countries that start with 'Q'",
    "what can you read ",
    "countries that start with 'E'",
    "things you can't buy on amazon",
    "companies that start with 'V'",
    "Ball sports ",
    "Natural disasters",
    "male names that start with 'E'",
    "things a snake eats",
    "watersports ",
    "Camera brands ",
    "jobs that start with 'E'",
    "countries that start with 'F'",
    "Rooms in an apartment ",
    "countries that start with 'J'",
    "female names that start with 'B'",
    "male names that start with 'Q'",
    "plants",
    "male names that start with 'O'",
    "The ten commandments ",
    "Computer brands ",
    "Brass instruments ",
    "female names that start with 'F'",
    "companies that start with 'B'",
    "Woodwind instruments ",
    "Words with 'night' ",
    "Types of fat",
    "Cowboy equipment ",
    "other words for money ",
    "Activities when driving a car ",
    "Burgers at McDonald's ",
    "Faceparts ",
    "French names",
    "floor coverings ",
    "Names that start with 'W'",
    "countries that start with 'L'",
    "Abbreviations of organizations ",
    "companies that start with 'L'",
    "things most people are afraid of",
    "Religious communities ",
    "Spanish cities ",
    "Crimes ",
    "Designation for small people",
    "male names that start with 'F'",
    "Fruits ",
    "movies starring Bryan Cranston",
    "Soups ",
    "Lakes in Europe ",
    "Names that start with 'D'",
    "male names that start with 'U'",
    "Sources of energy ",
    "classical composers ",
    "islands in the Mediterranean ",
    "jobs that start with 'B'",
    "companies that start with 'Q'",
    "Cities in Great Britain ",
    "Chess pieces ",
    "US states",
    "things in a Chinese restaurant",
    "things in the trunk ",
    "apostles ",
    "jobs that start with 'L'",
    "songs by Drake ",
    "songs by Johnny Cash",
    "what can you write with ",
    "Bones in the human body",
    "Parts of a car ",
    "types of Noodles ",
    "Terms at roulette ",
    "cigarette brands ",
    "male names that start with 'S'",
    "countries that start with 'M'",
    "another word for stupid  ",
    "Names that start with 'L'",
    "jobs that start with 'F'",
    "Names that start with 'A'",
    "countries that start with 'W'",
    "Hobbies ",
    "songs by Michael Jackson",
    "presidents of the USA ",
    "Names that start with 'T'",
    "Neighboring countries from Germany ",
    "Beer brands",
    "actors with first name 'Tom' ",
    "flowers ",
    "things in a museum",
    "male names that start with 'M'",
    "Mushrooms ",
    "movies starring Morgan Freeman",
    "salty things ",
    "countries that start with 'S'",
    "Things that are red ",
    "male names that start with 'I'",
    "countries that start with 'D'",
    "male names that start with 'D'",
    "things you should not mix with water",
    "types of Firearms ",
    "male names that start with 'C'",
    "what is eaten cold ",
    "male names that start with 'H'",
    "companies that start with 'S'",
    "Northern states of the USA ",
    "famous emperors ",
    "jobs that start with 'O'",
    "Winter clothing ",
    "female names that start with 'D'",
    "countries that start with 'P'",
    "cities in France ",
    "sporting goods ",
    "Names that start with 'F'",
    "compound first names ",
    "movies starring Matt Damon",
    "Car tire brands ",
    "companies that start with 'P'",
    "Asian tribes ",
    "Words with 'large' ",
    "Names that start with 'C'",
    "coffee brands",
    "movies by Steven Spielberg ",
    "Dances ",
    "places to hide drugs",
    "Technical devices in the household",
    "jobs that start with 'K'",
    "Figures from the Old Testament ",
    "containers for liquids",
    "countries that start with 'U'",
    "Car brands ",
    "Greek letters ",
    "Summer sports ",
    "subjects in School",
    "large lakes ",
    "companies that start with 'W'",
    "Greek gods ",
    "things a craftsman needs ",
    "Names that start with 'J'",
    "things that are gray ",
    "female names that start with 'T'",
    "Countries in which you speak English ",
    "Words that start with 'Fire...'",
    "female names that start with 'Q'",
    "things on your bucketlist",
    "movies starring Robert De Niro",
    "What you need water for",
    "things that are blue",
    "What is available at the gas station ",
    "colors on a rubics cube",
    "male names that start with 'A'",
    "male names that start with 'K'",
    "Girl names with 4 letters",
    "people in uniform ",
    "African countries",
    "Countries in South America",
    "jobs that start with 'T'",
    "companies that start with 'M'",
    "Names that start with 'Q'",
    "islands in the Atlantic ",
    "female names that start with 'A'",
    "male names that start with 'R'",
    "songs by Elvis Presley",
    "words that start with books ",
    "Parts of a camera",
    "male names that start with 'G'",
    "Fruits types ",
    "Things that are white ",
    "companies that start with 'O'",
    "companies that start with 'G'",
    "Names that start with 'S'",
    "movies starring The Rock ",
    "female names that start with 'G'",
    "spanish speaking countries",
    "cities in Germany ",
    "jobs that start with 'P'",
    "countries larger that the US",
    "jobs that start with 'R'",
    "movies starring Margot Robbie",
    "female names that start with 'C'",
    "movies starring Scarlett Johansson",
    "female names that start with 'L'",
    "Names that start with 'R'",
    "Names that start with 'I'",
    "companies that start with 'J'",
    "cities in Europe ",
    "movies starring Robert Downey Jr.",
    "jobs that start with 'I'",
    "Dog breeds ",
    "jobs that start with 'Q'",
    "female names that start with 'N'",
    "movies starring Tom Cruise",
    "island n in the Pacific ",
    "Names that start with 'N'",
    "Winter Sports ",
    "things in ancient egypt",
    "Newspapers ",
    "human rights ",
    "famous ships",
    "male names that start with 'N'",
    "watch brand ",
    "cities in California",
    "Capitals in Asia ",
    "what can be found under a sink  ",
    "billionairs ",
    "Gemstones ",
    "countries that start with 'T'",
    "Mediterranean countries ",
    "Remedies for insomnia ",
    "Sesame Street Members ",
    "jobs that start with 'M'",
    "Herbs ",
    "Japanese companies ",
    "movies starring Ryan Gosling",
    "Famous scientists ",
    "female names that start with 'J'",
    "things that are yellow ",
    "Most populous countries ",
    "",
    "soft drinks ",
    "jewelry for women ",
    "male names that start with 'B'",
    "type of bears ",
    "Names that start with 'P'",
    "jobs that start with 'U'",
    "Things in the kitchen ",
    "jobs that start with 'V'",
    "countries that start with 'H'",
    "jobs that start with 'N'",
    "countries that start with 'V'",
    "Letters in the alphabet ",
    "movies starring Jennifer Lawrence",
    "words with 'apple' ",
    "jobs that start with 'S'",
    "jobs that start with 'A'",
    "things in the classroom ",
    "departments in the supermarket ",
    "Words that start with 'Ex...'",
    "Words with 'mother' ",
    "types of schools ",
    "movies starring Anthony Hopkins",
    "countries that start with 'K'",
    "Boxers ",
    "Wooden things ",
    "Names that start with 'B'",
    "movies starring Will Smith",
    "jobs that start with 'W'",
    "String instruments ",
    "songs by Elton John",
    "things that does not fit in your mouth",
    "What rings ",
    "songs by Phil Collins",
    "skiing equipment",
    "Things that are yellow ",
    "parts of a plane",
    "companies that start with 'I'",
    "female names that start with 'K'",
    "Inventers",
    "film studios ",
    "countries that start with 'O'",
    "things you mix with wodka",
    "that you can be addicted to ",
    "Sparkling wine Champagne brands ",
    "Olympic Winter Games Disciplines ",
    "cities in Cuba ",
    "Cheeses ",
    "Names that start with 'G'",
    "childhood diseases",
    "things that are green ",
    "companies that start with 'N'",
    "movies starring Liam Neeson",
    "Familymembers of the English Royalty ",
    "banks ",
    "European capitals ",
    "members of the NATO",
    "philosophers ",
    "best-selling authors ",
    "female names that start with 'P'",
    "Bird species ",
    "Fruit juices ",
    "companies that start with 'A'",
    "countries that start with 'R'",
    "jobs that start with 'C'",
    "Types of execution Fonts ",
    "countries that start with 'A'",
    "Potato dishes ",
    "male names that start with 'T'",
    "Perfume brands ",
    "Medical terms ",
    "companies that start with 'U'",
    "life-threatening diseases ",
    "Names that start with 'H'",
    "boygroup bands",
    "Holidays activities",
    "companies that start with 'K'",
    "Languages ",
    "companies that start with 'D'",
    "things in a closet ",
    "Elements in the Periodic table",
    "Names that start with 'U'",
    "Music styles ",
    "countries in Africa",
    "edible fish",
    "things You don't smell ",
    "Things in the church ",
    "Baby equipment ",
    "songs by Paul McCartney",
    "jobs that start with 'H'",
    "Disney cartoons"
];
//indexes that have been used
let usedIndexes = [];
let infoVisible = false;
let animationOn = true;

//get the next topic via changeTopic() function
nextButton.addEventListener("click", changeTopic);

//show/remove info 
document.getElementById("infoButton").addEventListener("click", () => {
    document.getElementById("informationtext").style.visibility = (infoVisible) ? "hidden" : "visible";
    infoVisible = !infoVisible;
});

//toggle card anination 
document.querySelector("#animationCheckbox").addEventListener("change", () => {
    animationOn = !animationOn;
});

//function that changes the topic to the next random one and also changes the background topic
function changeTopic() {
    document.querySelector("#old-topic").innerHTML = document.querySelector("#topic").innerHTML;
    if (animationOn) {
        changeCard();
    }
    document.querySelector("#topic").innerHTML = topicArray[getRandomNumber()];
}

//card transition animation
function changeCard() {
    document.querySelector("#header").animate([
        { transform: "translateY(-800px)" },
        { transform: "translateY(0px)" }
    ], {
        duration: 1000,
        iterations: 1,
        fill: "forwards"
    });
}

//gets a random number between 0 and the length of the array (new topic) and checks if it has been used before (if yes, it gets a new number)
function getRandomNumber() {

    //gets a random index 
    let random = Math.floor(Math.random() * topicArray.length);

    //checks if the topic is already used
    if (usedIndexes.includes(random)) {
        if (usedIndexes.length === topicArray.length) {
            usedIndexes = [];
        }
        return getRandomNumber();
    } else {
        usedIndexes.push(random);
        return random;
    }

}
